"""extend user table

Revision ID: 44aadc2561d5
Revises: a9dbf679b901
Create Date: 2019-05-23 22:13:02.775944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44aadc2561d5'
down_revision = 'a9dbf679b901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
