"""add company_detail table

Revision ID: 89522e3df250
Revises: 112bc54aba95
Create Date: 2019-05-24 13:04:25.883121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89522e3df250'
down_revision = '112bc54aba95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_detail',
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('logo', sa.String(length=64), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=124), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('about', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_detail')
    # ### end Alembic commands ###
