"""extend user table

Revision ID: 965ea7df9e19
Revises: 2c38a3696e24
Create Date: 2019-05-23 21:18:21.847116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965ea7df9e19'
down_revision = '2c38a3696e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('real_name', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('resume_url', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('work_years', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_user_real_name'), 'user', ['real_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_real_name'), table_name='user')
    op.drop_column('user', 'work_years')
    op.drop_column('user', 'resume_url')
    op.drop_column('user', 'real_name')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
