"""extend job table

Revision ID: aa5ce6ccfa23
Revises: cae1063016f2
Create Date: 2019-05-24 22:13:38.944723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa5ce6ccfa23'
down_revision = 'cae1063016f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('logo', sa.String(length=128), nullable=False))
    op.drop_column('company_detail', 'logo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('logo_url', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('company_detail', 'logo')
    # ### end Alembic commands ###
