"""add job table

Revision ID: b996849a42c5
Revises: 29881ec2b2a4
Create Date: 2019-05-24 20:36:40.875194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b996849a42c5'
down_revision = '29881ec2b2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('field', sa.String(length=128), nullable=True))
    op.add_column('company_detail', sa.Column('finance_stage', sa.String(length=128), nullable=True))
    op.add_column('company_detail', sa.Column('stack', sa.String(length=128), nullable=True))
    op.add_column('company_detail', sa.Column('tags', sa.String(length=128), nullable=True))
    op.add_column('company_detail', sa.Column('team_introduction', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_detail', 'team_introduction')
    op.drop_column('company_detail', 'tags')
    op.drop_column('company_detail', 'stack')
    op.drop_column('company_detail', 'finance_stage')
    op.drop_column('company_detail', 'field')
    # ### end Alembic commands ###
