"""extend job table

Revision ID: cae1063016f2
Revises: b996849a42c5
Create Date: 2019-05-24 22:12:46.654024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cae1063016f2'
down_revision = 'b996849a42c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('logo_url', sa.String(length=128), nullable=False))
    op.drop_column('company_detail', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('logo', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('company_detail', 'logo_url')
    # ### end Alembic commands ###
